WIP: Js/remove ns
IntersectMBO/ouroboros-consensus pull request #1135
Opened 2024-06-04 14:15 UTC by jasagredo

# Description

Please include a meaningful description of the PR and link the relevant issues
this PR might resolve.

Also note that:

- New code should be properly tested (even if it does not add new features).
- The fix for a regression should include a test that reproduces said regression.

2024-06-09 16:13 UTC, jorisdral requested changes

2024-06-09 16:13 UTC, jorisdral commented on ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Ledger.hs
> +  distribHardForkTxOut (IS (IS (IS (IS (IS (IS (IS idx))))))) = case idx of {}
Unfortunate that this now has a quadratic number of cases, but there is no way around that I can see! (for now)

2024-06-09 16:13 UTC, jorisdral commented on ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Ledger.hs
>  -- implementation.
```suggestion
```

2024-06-17 12:56 UTC, jasagredo commented on ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Ledger.hs
> +      <> encodeValue (getLedgerTables $ codecLedgerTables @(LedgerState (ShelleyBlock (TPraos c) (AllegraEra c)))) txout
Done

2024-06-17 12:57 UTC, merged