Typed Protocols: new API
IntersectMBO/ouroboros-consensus pull request #1223
Opened 2024-08-21 09:50 UTC by coot

# Description

- **Updated to use typed-protocols-0.2.0.0**
- **Added KeepAlive tracer**
- **ouroboros-network deprecated TxSizeInBytes**

2024-10-01 15:12 UTC, nfrisby requested changes
The PR description seems a bit off. 
![image](https://github.com/user-attachments/assets/cea63d5b-fecb-4636-9b6f-6f7da03653cd)

- It's version 0.3.0.0, not version 0.2.0.0.
- I don't see any aspects of `SizeInBytes` within the diff itself.

The diff itself looked totally fine. I don't follow the new `Stateful` stuff yet, but everything here seems very reasonable.

I'm not Approving because of:

1) The above concerns about the PR description.
2) I don't think we want an `source-repository-package` stanza on the `main` branch. Will the relevant dependencies be uploaded to CHaP soon enough to wait for them?

2024-10-01 15:16 UTC, coot commented
I started with `t-p-0.2` and ended up with `t-p-0.3` :grin:.  The `TxSizeInBytes` patch is gone from this PR, due to consensus introducing its own sizes in a recent PR.

2024-10-03 09:00 UTC, crocodile-dentist commented
ekg-forward 0.6 which is going into the next node release is incompatible with new typed-protocols 0.3 so lets hold off on merging this PR.

2024-10-17 18:13 UTC, coot commented
@crocodile-dentist `ekg-forward` is not a dependency of `ouroboros-consensus`; I have a [draft PR](https://github.com/input-output-hk/ekg-forward/pull/33) for it as well (as for all other `cardano-node` dependencies :smiley:).

2024-10-21 08:51 UTC, crocodile-dentist commented
> @crocodile-dentist `ekg-forward` is not a dependency of `ouroboros-consensus`; I have a [draft PR](https://github.com/input-output-hk/ekg-forward/pull/33) for it as well (as for all other `cardano-node` dependencies 😃).

Yes, but it would have caused problems downstream when releasing node - consensus would have to release off branch to make it go smoothest.

2024-10-21 14:15 UTC, amesgen approved these changes

2024-10-21 14:52 UTC, coot commented on ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/IOLike.hs
> +      , MonadLabelledSTM        m
It seems impossible to define `instance MonadTraceSTM (OverrideDelay m)` right now.  One needs:
```fn
fn :: proxy (OverrideDelay m) -> proxy m
fn = undefined
```

We need to switch from a polymorphic `proxy` type to `Proxy` in `MonadTraceTVar`.

Here are the definitions which compiled for me:
```hs
instance MonadInspectSTM m => MonadInspectSTM (OverrideDelay m) where
  type InspectMonad (OverrideDelay m) = InspectMonad m
  inspectTVar p v = inspectTVar p v
  inspectTMVar p v = inspectTMVar p v

fn :: proxy (OverrideDelay m) -> proxy m
fn = undefined

instance MonadTraceSTM m => MonadTraceSTM (OverrideDelay m) where
  traceTVar p v f  = OverrideDelaySTM . lift $ LazySTM.traceTVar (fn p) v f
  traceTMVar p v f = OverrideDelaySTM . lift $ LazySTM.traceTMVar (fn p) v f
  traceTQueue p v f = OverrideDelaySTM . lift $ LazySTM.traceTQueue (fn p) v f
  traceTBQueue p v f = OverrideDelaySTM . lift $ LazySTM.traceTBQueue (fn p) v f
  traceTSem p v f = OverrideDelaySTM . lift $ LazySTM.traceTSem (fn p) v f
```

If we used `Proxy`, then `fn Proxy = Proxy` should work.

2024-10-21 15:05 UTC, amesgen commented on ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/IOLike.hs
> +      , MonadLabelledSTM        m
But the `proxy`s don't need to be the same, right?
```haskell
fn :: proxy (OverrideDelay m) -> Proxy m
fn _ = Proxy
```
should do the job.

2024-10-21 17:35 UTC, coot commented on ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/IOLike.hs
> +      , MonadLabelledSTM        m
yes, I realised that when I was driving... :grin:

2024-10-21 17:46 UTC, amesgen commented on ouroboros-consensus/test/consensus-test/Test/Consensus/BlockchainTime/Simple.hs
> +  inspectTMVar = inspectTMVar
Won't this loop at runtime? I think we need to supply `Proxy @m`

2024-10-21 18:26 UTC, merged